// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/artists': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/artists/index').default>>>>
    }
    '/api/intros': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/intros/index').default>>>>
    }
    '/api/notifications': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/index').default>>>>
    }
    '/api/portfolios': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/portfolios/index').default>>>>
    }
    '/api/services': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/services/index').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}