export default defineEventHandler((event) => {
    return [
        {
            id: 1,
            title: 'خدمات ناخن',
            description: 'خدمات ناخن',
            rating: 4.5,
            price: 100000,
            discount_price: 90000,
            is_bookmarked: true,
            has_tel: true,
            has_phone_number: false,
            showing_phone_number: '09381412419',
            service_id: 1,
            service: {
                id: 1,
                title: "خدمات ناخن",
                image: "https://via.placeholder.com/57x57.png/00ddaa?text=minus",
                is_active: 1,
                parent_id: null,
                created_at: "2024-04-12T16:14:23.000000Z",
                updated_at: "2024-04-12T16:14:23.000000Z"
            },
            user_id: 1,
            user: {
                id: 1,
                full_name: "زیبا اعظمی",
                phone_number: '09381412419',
            },
            images: ['/images/artist/1.jpg', '/images/artist/1.jpg'],
            work_hours: []
        },
        {
            id: 2,
            title: 'خدمات ناخن',
            description: 'خدمات ناخن',
            rating: 4.5,
            price: 100000,
            discount_price: 90000,
            is_bookmarked: true,
            has_tel: true,
            has_phone_number: false,
            showing_phone_number: '09381412419',
            service_id: 1,
            service: {
                id: 1,
                title: "خدمات ناخن",
                image: "https://via.placeholder.com/57x57.png/00ddaa?text=minus",
                is_active: 1,
                parent_id: null,
                created_at: "2024-04-12T16:14:23.000000Z",
                updated_at: "2024-04-12T16:14:23.000000Z"
            },
            user_id: 1,
            user: {
                id: 1,
                full_name: "زیبا اعظمی",
                phone_number: '09381412419',
            },
            images: ['/images/artist/1.jpg', '/images/artist/1.jpg'],
            work_hours: []
        },
        {
            id: 3,
            title: 'خدمات ناخن',
            description: 'خدمات ناخن',
            rating: 4.5,
            price: 100000,
            discount_price: 90000,
            is_bookmarked: false,
            has_tel: true,
            has_phone_number: false,
            showing_phone_number: '09381412419',
            service_id: 1,
            service: {
                id: 1,
                title: "خدمات ناخن",
                image: "https://via.placeholder.com/57x57.png/00ddaa?text=minus",
                is_active: 1,
                parent_id: null,
                created_at: "2024-04-12T16:14:23.000000Z",
                updated_at: "2024-04-12T16:14:23.000000Z"
            },
            user_id: 1,
            user: {
                id: 1,
                full_name: "زیبا اعظمی",
                phone_number: '09381412419',
            },
            images: ['/images/artist/1.jpg', '/images/artist/1.jpg'],
            work_hours: []
        },
        {
            id: 4,
            title: 'خدمات ناخن',
            description: 'خدمات ناخن',
            rating: 4.5,
            price: 100000,
            discount_price: 90000,
            has_tel: true,
            is_bookmarked: false,
            has_phone_number: false,
            showing_phone_number: '09381412419',
            service_id: 1,
            service: {
                id: 1,
                title: "خدمات ناخن",
                image: "https://via.placeholder.com/57x57.png/00ddaa?text=minus",
                is_active: 1,
                parent_id: null,
                created_at: "2024-04-12T16:14:23.000000Z",
                updated_at: "2024-04-12T16:14:23.000000Z"
            },
            user_id: 1,
            user: {
                id: 1,
                full_name: "زیبا اعظمی",
                phone_number: '09381412419',
            },
            images: ['/images/artist/1.jpg', '/images/artist/1.jpg'],
            work_hours: []
        },
        {
            id: 5,
            title: 'خدمات ناخن',
            description: 'خدمات ناخن',
            rating: 4.5,
            price: 100000,
            discount_price: 90000,
            is_bookmarked: true,
            has_tel: true,
            has_phone_number: false,
            showing_phone_number: '09381412419',
            service_id: 1,
            service: {
                id: 1,
                title: "خدمات ناخن",
                image: "https://via.placeholder.com/57x57.png/00ddaa?text=minus",
                is_active: 1,
                parent_id: null,
                created_at: "2024-04-12T16:14:23.000000Z",
                updated_at: "2024-04-12T16:14:23.000000Z"
            },
            user_id: 1,
            user: {
                id: 1,
                full_name: "زیبا اعظمی",
                phone_number: '09381412419',
            },
            images: ['/images/artist/1.jpg', '/images/artist/1.jpg'],
            work_hours: []
        },
        {
            id: 6,
            title: 'خدمات ناخن',
            description: 'خدمات ناخن',
            rating: 4.5,
            price: 100000,
            discount_price: 90000,
            is_bookmarked: true,
            has_tel: true,
            has_phone_number: false,
            showing_phone_number: '09381412419',
            service_id: 1,
            service: {
                id: 1,
                title: "خدمات ناخن",
                image: "https://via.placeholder.com/57x57.png/00ddaa?text=minus",
                is_active: 1,
                parent_id: null,
                created_at: "2024-04-12T16:14:23.000000Z",
                updated_at: "2024-04-12T16:14:23.000000Z"
            },
            user_id: 1,
            user: {
                id: 1,
                full_name: "زیبا اعظمی",
                phone_number: '09381412419',
            },
            images: ['/images/artist/1.jpg', '/images/artist/1.jpg'],
            work_hours: []
        },
        {
            id: 7,
            title: 'خدمات ناخن',
            description: 'خدمات ناخن',
            rating: 4.5,
            price: 100000,
            discount_price: 90000,
            is_bookmarked: false,
            has_tel: true,
            has_phone_number: false,
            showing_phone_number: '09381412419',
            service_id: 1,
            service: {
                id: 1,
                title: "خدمات ناخن",
                image: "https://via.placeholder.com/57x57.png/00ddaa?text=minus",
                is_active: 1,
                parent_id: null,
                created_at: "2024-04-12T16:14:23.000000Z",
                updated_at: "2024-04-12T16:14:23.000000Z"
            },
            user_id: 1,
            user: {
                id: 1,
                full_name: "زیبا اعظمی",
                phone_number: '09381412419',
            },
            images: ['/images/artist/1.jpg', '/images/artist/1.jpg'],
            work_hours: []
        },
        {
            id: 8,
            title: 'خدمات ناخن',
            description: 'خدمات ناخن',
            rating: 4.5,
            price: 100000,
            discount_price: 90000,
            is_bookmarked: false,
            has_tel: true,
            has_phone_number: false,
            showing_phone_number: '09381412419',
            service_id: 1,
            service: {
                id: 1,
                title: "خدمات ناخن",
                image: "https://via.placeholder.com/57x57.png/00ddaa?text=minus",
                is_active: 1,
                parent_id: null,
                created_at: "2024-04-12T16:14:23.000000Z",
                updated_at: "2024-04-12T16:14:23.000000Z"
            },
            user_id: 1,
            user: {
                id: 1,
                full_name: "زیبا اعظمی",
                phone_number: '09381412419',
            },
            images: ['/images/artist/1.jpg', '/images/artist/1.jpg'],
            work_hours: []
        },
        {
            id: 9,
            title: 'خدمات ناخن',
            description: 'خدمات ناخن',
            rating: 4.5,
            price: 100000,
            discount_price: 90000,
            is_bookmarked: false,
            has_tel: true,
            has_phone_number: false,
            showing_phone_number: '09381412419',
            service_id: 1,
            service: {
                id: 1,
                title: "خدمات ناخن",
                image: "https://via.placeholder.com/57x57.png/00ddaa?text=minus",
                is_active: 1,
                parent_id: null,
                created_at: "2024-04-12T16:14:23.000000Z",
                updated_at: "2024-04-12T16:14:23.000000Z"
            },
            user_id: 1,
            user: {
                id: 1,
                full_name: "زیبا اعظمی",
                phone_number: '09381412419',
            },
            images: ['/images/artist/1.jpg', '/images/artist/1.jpg'],
            work_hours: []
        },
    ];
});