export default defineEventHandler((event) => {
    return [
        {
            id: 1,
            full_name: 'حدیثه شریفی',
            has_blue_tick: true,
            created_at_ago_fa: '1 سال و 2 ماه',
            portfolios_count: 15,
            services_count: 2,
            address: 'سالن زیبایی عروس',
            distance: '17km',
            rating: 4.5,
            is_bookmarked: true,
            avatar: '/images/artist/2.png'
        },
        {
            id: 2,
            full_name: 'حدیثه شریفی',
            has_blue_tick: true,
            created_at_ago_fa: '1 سال و 2 ماه',
            portfolios_count: 15,
            services_count: 2,
            address: 'سالن زیبایی عروس',
            distance: '17km',
            rating: 4.5,
            is_bookmarked: true,
            avatar: '/images/artist/2.png'
        },
        {
            id: 3,
            full_name: 'حدیثه شریفی',
            has_blue_tick: true,
            created_at_ago_fa: '1 سال و 2 ماه',
            portfolios_count: 15,
            services_count: 2,
            address: 'سالن زیبایی عروس',
            distance: '17km',
            rating: 4.5,
            is_bookmarked: true,
            avatar: '/images/artist/2.png'
        },
        {
            id: 4,
            full_name: 'حدیثه شریفی',
            has_blue_tick: true,
            created_at_ago_fa: '1 سال و 2 ماه',
            portfolios_count: 15,
            services_count: 2,
            address: 'سالن زیبایی عروس',
            distance: '17km',
            rating: 4.5,
            is_bookmarked: true,
            avatar: '/images/artist/2.png'
        },
        {
            id: 5,
            full_name: 'حدیثه شریفی',
            has_blue_tick: true,
            created_at_ago_fa: '1 سال و 2 ماه',
            portfolios_count: 15,
            services_count: 2,
            address: 'سالن زیبایی عروس',
            distance: '17km',
            rating: 4.5,
            is_bookmarked: true,
            avatar: '/images/artist/2.png'
        },
        {
            id: 6,
            full_name: 'حدیثه شریفی',
            has_blue_tick: true,
            created_at_ago_fa: '1 سال و 2 ماه',
            portfolios_count: 15,
            services_count: 2,
            address: 'سالن زیبایی عروس',
            distance: '17km',
            rating: 4.5,
            is_bookmarked: true,
            avatar: '/images/artist/2.png'
        },
        {
            id: 7,
            full_name: 'حدیثه شریفی',
            has_blue_tick: true,
            created_at_ago_fa: '1 سال و 2 ماه',
            portfolios_count: 15,
            services_count: 2,
            address: 'سالن زیبایی عروس',
            distance: '17km',
            rating: 4.5,
            is_bookmarked: true,
            avatar: '/images/artist/2.png'
        },
        {
            id: 8,
            full_name: 'حدیثه شریفی',
            has_blue_tick: true,
            created_at_ago_fa: '1 سال و 2 ماه',
            portfolios_count: 15,
            services_count: 2,
            address: 'سالن زیبایی عروس',
            distance: '17km',
            rating: 4.5,
            is_bookmarked: true,
            avatar: '/images/artist/2.png'
        },
        {
            id: 9,
            full_name: 'حدیثه شریفی',
            has_blue_tick: true,
            created_at_ago_fa: '1 سال و 2 ماه',
            portfolios_count: 15,
            services_count: 2,
            address: 'سالن زیبایی عروس',
            distance: '17km',
            rating: 4.5,
            is_bookmarked: true,
            avatar: '/images/artist/2.png'
        },
        {
            id: 10,
            full_name: 'حدیثه شریفی',
            has_blue_tick: true,
            created_at_ago_fa: '1 سال و 2 ماه',
            portfolios_count: 15,
            services_count: 2,
            address: 'سالن زیبایی عروس',
            distance: '17km',
            rating: 4.5,
            is_bookmarked: true,
            avatar: '/images/artist/2.png'
        },
    ];
});